### ISSUE TITLE
Не могу поставить видео на пластинку

### ISSUE THREAD

**Issue by 1ketch1** [plasmoapp/pv-addon-discs#49] opened 2024-04-18 16:22 UTC
![image](https://github.com/plasmoapp/pv-addon-discs/assets/167456725/e3f35baf-e25d-4fb8-b8dc-fce29d396a50)

**Comment by Apehum** [comment] 2024-04-20 18:56
Поставь пререлиз pv-addon-lavaplayer-lib: https://github.com/plasmoapp/pv-addon-lavaplayer-lib/releases/tag/1.0.8

Duplicate of #48

**Closed by Apehum** 2024-04-20 18:56 UTC
